### ISSUE TITLE
Duplicated keys in record

### ISSUE THREAD

**Issue by eapyl** [MaybeJustJames/yaml#24]
Hello,

It seems like the library ignores duplicated keys silently
```
root:
  item1:
    name: Item1
  item1:
    name: Item 2
```
and it seems like cause [`Dict.fromList` is used on the list without duplication check](https://github.com/MaybeJustJames/yaml/blob/2.1.0/src/Yaml/Decode.elm#L389). Is it expected behavior?
It feels for me that it should produce an error in such cases. Or am I wrong?
Thanks
