### ISSUE TITLE
Fails to encode multi-line strings (and other yaml string bugs)

### ISSUE THREAD

**Issue by kageurufu** [MaybeJustJames/yaml#37]
I need to encode multi-line strings within a record, that often contain quotes. As well, I have octal permissions such as `0644` that yaml would parse as an octal numeric literal. I would expect `Encode.string` to either properly escape and quote this, or generate a yaml multi-line string block.

```yaml
escapeme: "0700"
oneline: "multi line string\nwith \"quoted\" text"
multiline: |-
  multi line string
  with "quoted" text
```

For now I'm working around this with the following:

```elm 
safeEncodeString : String -> YE.Encoder
safeEncodeString =
    encodeNewlines
        >> encodeQuotes
        >> String.Extra.quote
        >> YE.string


encodeNewlines : String -> String
encodeNewlines =
    String.replace "\n" "\\n"


encodeQuotes : String -> String
encodeQuotes s =
    if String.contains "\"" s then
        String.replace "\"" "\\\"" s

    else
        s
```
